remote_theme: jekyll/minima@v2.5.1

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

author: Luka Rekhviashvili

minima:
  hide_site_feed_link: true
  social_links:
    - title: Jekyll repository at GitHub
      icon: github
      url: "https://github.com/jekyll/jekyll"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/jekyllrb"
